package json2go

// json-gen OMIT
type AutoGenerated struct {
	Args struct {
	} `json:"args"`
	Headers struct {
		Accept                  string `json:"Accept"`
		AcceptEncoding          string `json:"Accept-Encoding"`
		AcceptLanguage          string `json:"Accept-Language"`
		Host                    string `json:"Host"`
		Referer                 string `json:"Referer"`
		SecFetchDest            string `json:"Sec-Fetch-Dest"`
		SecFetchMode            string `json:"Sec-Fetch-Mode"`
		SecFetchSite            string `json:"Sec-Fetch-Site"`
		UpgradeInsecureRequests string `json:"Upgrade-Insecure-Requests"`
		UserAgent               string `json:"User-Agent"`
		XAmznTraceID            string `json:"X-Amzn-Trace-Id"`
	} `json:"headers"`
	Origin string `json:"origin"`
	URL    string `json:"url"`
}
// json-gen OMIT
